name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files for debugging
      run: |
        ls -R
        pwd  # Print current directory

    - name: List tests directory contents
      run: |
        ls -R tests

    - name: Run tests
      env:
        PYTHONPATH: .
      run: |
        pytest -v
